version: "3"
services:
  web:
    build: .
    env_file:
      - app.env
    ports:
      - "5000:5000"
  redis:
    image: "redis:latest"
  tor:
    image: "dperson/torproxy"
    restart: unless-stopped
    ports:
      - "8118:8118"
      - "9050:9050"
