name: docker-compose Sample CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image via docker-compose
      run: docker-compose up --build --detach
    - name: Check logs
      run: docker-compose logs
